esphome:
  name: "sebaschan"
  platform: ESP8266
  board: nodemcuv2
  on_boot:
  # Indicating boot with that.
    - delay: 0.1s
    - switch.turn_on: t_pickup
    - delay: 0.1s
    - switch.turn_off: t_pickup
    - delay: 0.1s
    - switch.turn_on: t_pickup
    - delay: 0.1s
    - switch.turn_off: t_pickup

api: !secret api
ota: !secret ota
wifi: !secret wifi
logger:

switch:
  - platform: gpio
    pin:
      number: D3
      mode: OUTPUT_OPEN_DRAIN
      inverted: true
    id: ring_one
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: D5
    id: counter_up
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin:
      number: GPIO12
      mode: OUTPUT_OPEN_DRAIN
      inverted: true
    id: pickup
    restore_mode: ALWAYS_OFF

  - platform: template
    name: "Pick up phone"
    id: t_pickup
    lambda: |-
      return !digitalRead(12);
    turn_on_action:
      - switch.turn_on: pickup
    turn_off_action:
      - switch.turn_off: pickup

  - platform: template
    name: "Open Ring One Door"
    id: t_ring_one
    lambda: |-
      return !digitalRead(D3);
    turn_on_action:
      - switch.turn_on: counter_up
      - switch.turn_on: ring_one
      - delay: 0.05s
      - switch.turn_off: counter_up
    turn_off_action:
      - switch.turn_off: ring_one

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    filters:
      - delayed_on: 1ms
      - delayed_off: 2s
    name: "Call ring"
    on_press:
      then:
        - delay: 2s
        - switch.turn_on: t_pickup
        - delay: 2s
        - switch.turn_off: t_pickup
